Refactored the Code and Changes the function Name
NJACKWinterOfCode/Tabs-Share pull request #14
Opened 2018-12-15 04:09 UTC by rkishan516

Fixes #[3]
Fixes #[5]

Changes: [Refactored the Code and Changes the function Name.]

2018-12-15 04:11 UTC, rkishan516 commented
@Akshat-Jain Please look at it.

2018-12-17 09:50 UTC, rkishan516 commented
@Akshat-Jain I have sent the PR to him but He is unable to resolve the issue so this is the final PR from my side for both.

2018-12-24 04:13 UTC, rkishan516 commented
@Akshat-Jain I have done this PR 9 days ago till now no response.

2018-12-24 10:47 UTC, akshatnitd requested changes

2018-12-24 10:47 UTC, akshatnitd commented on js/main.css
> +	width:15px;
Please use consistent spacing here.

2018-12-24 10:47 UTC, akshatnitd commented on popup.js
>              b=[];
Please name the variables like a, b appropiately.

2018-12-24 12:36 UTC, rkishan516 commented
@Akshat-Jain Please look once again

2018-12-25 07:14 UTC, rkishan516 commented
@akshatnitd Please look at it.

2018-12-25 07:28 UTC, akshatnitd commented on js/main.css
> +	width:15px;
The spacing is not consistent. It should be `width: 15px;`

2018-12-25 07:41 UTC, rkishan516 commented
@akshatnitd please now check.

2018-12-25 10:48 UTC, rkishan516 commented
@akshatnitd Please check it.

2018-12-25 15:11 UTC, akshatnitd approved these changes
Looks good :+1:

2018-12-25 15:11 UTC, merged